# -*- coding: utf-8 -*-
"""Sevilla_Final Exam:

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wdnpOCfulqvmsKYyNKoRAJxDdjIZw0yx
"""

import streamlit as st
import tensorflow as tf

@st.cache_resource
def load_model():
  model=tf.keras.models.load_model('flowers_classification.h5')
  return model
model=load_model()
st.write("""
# Flower Classification"""
)
file=st.file_uploader("Upload a flower photo from your computer.",type=["jpg","png"])

import cv2
from PIL import Image,ImageOps
import numpy as np
def import_and_predict(image_data,model):
    size=(60,60)
    image=ImageOps.fit(image_data,size,Image.ANTIALIAS)
    img=np.asarray(image)
    img_reshape=img[np.newaxis,...]
    prediction=model.predict(img_reshape)
    return prediction
if file is None:
    st.text("Please upload an image of the flower (sunflower, rose, tulip, dandelion, daisy).")
else:
    image=Image.open(file)
    st.image(image,use_column_width=True)
    prediction=import_and_predict(image,model)
    class_names = ['tulip', 'sunflower', 'rose', 'dandelion', 'daisy']
    string="THE FLOWER IS : "+class_names[np.argmax(prediction)]
    st.success(string)

    
   # Adding a sidebar
st.sidebar.title("Menu")
selected_option = st.sidebar.selectbox("Select", ("About", "Help", "GitHub Link", "Conclusion"))

if selected_option == "About":
    st.sidebar.write("It is a flower dataset that contains 50 images per flower class for flower classification")
    st.sidebar.write("")
    st.sidebar.write("Author:")
    st.sidebar.write("Name: Sevilla, Mylen B.")
    st.sidebar.write("Section and Grade: CPE32S4")
    st.sidebar.write("Instructor: Dr. Jonathan Taylar")

elif selected_option == "Help":
    st.sidebar.write("Choose an image related to flowers (rose, sunflower, tulip, dandelion,daisy)")
    st.sidebar.write("Upload a flower image")
    st.sidebar.write("Wait the results")
    
elif selected_option == "GitHub Link":
    st.sidebar.write("https://github.com/MylenSevilla/Streamlit/tree/main")

elif selected_option == "Conclusion":
    st.sidebar.write("To sum it up, this activity is all about the model deployment in the cloud and will serve as a final exam for the student. In this activity, the student trains a dataset that will predict the flower classification, saves the model, and deploys the deep learning model in the cloud. Through this activity, the student was able to learn why model deployment in the cloud is important; it is crucial for achieving scalability, cost-efficiency, reliability, worldwide accessibility, collaboration, and security. It enables organizations to effortlessly scale models as needed, reduce expenses through flexible pricing, ensure consistent availability, reach a global user base, facilitate teamwork, and leverage advanced security measures. Cloud deployment simplifies the process, optimizes model utilization, and minimizes operational challenges. Furthermore, the student was also able to understand the importance of using Streamlit due to its intuitive interface, rapid prototyping and iteration, smooth integration with popular machine learning frameworks, interactive visualization features, effortless collaboration and sharing options, and cost-effectiveness. By using Streamlit, students can deploy their models swiftly, design attractive user interfaces, collaborate efficiently, and effectively showcase their machine learning projects.")
